#ifndef FREELIB_CONFIG_FREELIB_H
#define FREELIB_CONFIG_FREELIB_H

#define FREELIB_DATA_DIR "@CMAKE_INSTALL_PREFIX@/@DATA_INSTALL_DIR@" 

#define FREELIB_VERSION "@FREELIB_VERSION@"

#endif // FREELIB_CONFIG_FREELIB_H
